### ISSUE TITLE
installing --without-shell-completion dies with an error

### ISSUE THREAD

**Issue by tdsmith** [erkin/ponysay#224]
Attempting to work around #223 we noticed that --without-shell-completion doesn't work. It dies instead:

```
::Installing...
Copying file ponysay.install to /usr/local/Cellar/ponysay/3.0.2/bin/ponysay
Creating symbolic link /usr/local/Cellar/ponysay/3.0.2/bin/ponythink with target file /usr/local/Cellar/ponysay/3.0.2/bin/ponysay
Creating symbolic link /usr/local/Cellar/ponysay/3.0.2/bin/ponysay-tool with target file /usr/local/Cellar/ponysay/3.0.2/bin/ponysay
Setting mode for ponysay.install copies to 755
Traceback (most recent call last):
  File "./setup.py", line 1190, in <module>
    Setup()
  File "./setup.py", line 292, in __init__
    self.install(conf)
  File "./setup.py", line 614, in install
    cmdarr = ['install-info', '--entry=Miscellaneous', '--description=' + conf['info-install'], '--dir-file=' + conf['info'] + '/dir', dest]
UnboundLocalError: local variable 'dest' referenced before assignment
```

**Comment by jristz** [comment]
I merged your push.

@maandree you did the spliting of completions and autoautocompletion thing, any word in why this happend?

**Comment by maandree** [comment]
I've fixed it, just missed to set the variable dest.
