### ISSUE TITLE
If a directory inside the current directory matches the name of a pony ponysay bails.

### ISSUE THREAD

**Issue by jristz** [erkin/ponysay#246]
IIn issue #240 user say that "If a directory inside the current directory matches the name of a pony ponysay bails." aparently the install script never check if there is such case and i suspect that because you can summon a pony just by he name is possible to ponysay take the first file and try to parse it indiferent if is a .pony file or not (like evwrything in a unix system is a file so a directory is a file like a .pony is a file).

So to prevent this is better as a case in the install script that remove any file not being a .pony file from the ponydirectory and add a check on ponysay parser that if a file not start with ponysatypical ponysay hea

**Comment by thePalindrome** [comment]
I feel I should mention this, since I haven't seen an update to the issue in quite some time:

I've installed ponysay using portage, so all of the ponysay files are in /usr/share/ponysay/
Installation works perfectly, as evidenced by the fact that my login script works perfectly.

If you run the following (assuming ponysay is in your path):
```
cd /tmp
mkdir twilight
ponysay -f twilight test
```

You will get a dump similar to this:

```
 Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/ponysay/__main__.py", line 154, in <module>
  File "/usr/bin/ponysay/ponysay.py", line 254, in run
  File "/usr/bin/ponysay/ponysay.py", line 305, in __run
  File "/usr/bin/ponysay/ponysay.py", line 929, in printPony
  File "/usr/bin/ponysay/backend.py", line 86, in parse
  File "/usr/bin/ponysay/backend.py", line 211, in __loadFile
IsADirectoryError: [Errno 21] Is a directory: 'twilight'
```
