### ISSUE TITLE
Please make it installable through pip

### ISSUE THREAD

**Issue by clonedagain** [erkin/ponysay#248]
Installing with the setup is rather easy, but it would be easier still if we could get ponysay through PIP.
Is it something you would consider?

**Comment by jristz** [comment]
There is a long long standing bug about port the installation to a proper python one (to suport python virtual env).

this is related but in this case request specificaly PIP(squeak ;p ).

I will let it open since they aproach the same issue but from different angles... aaand because i can find the intallation request.

(I'm artist and documenter not programer so any patch is welcome).

**Comment by jristz** [comment]
The bug is #94 talking about the build system.

still a work in progress since /setup.py was a "temporal" until we get the definitive, this bug talk specificaly to port to PIP intead of a more options like 94 so I will let it open.

**Comment by thorsummoner** [comment]
Because I feel frustrated and want to say soemthing but know there is nothing valuable I can say, here are the error messages python yields when trying to install this:
```
$ python2 -m pip install --user git+https://github.com/erkin/ponysay.git
Collecting git+https://github.com/erkin/ponysay.git
  Cloning https://github.com/erkin/ponysay.git to /tmp/pip-KA9XmJ-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-KA9XmJ-build/setup.py", line 1202
        print('\n\033[1mUSAGE:\033[21m', end='')
                                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-KA9XmJ-build/
```
"Oh its python 3 only, nothing wrong with that."

```
$ python3 -m pip install --user git+https://github.com/erkin/ponysay.git
Collecting git+https://github.com/erkin/ponysay.git
  Cloning https://github.com/erkin/ponysay.git to /tmp/pip-oywq__6i-build
    Complete output from command python setup.py egg_info:
    setup.py: fatal: Unrecognized option --egg-base. Use --help or consult the manual.
    
    ----------------------------------------
```
"Oh setup bug, Maybe I can offer a patch to fix it. *looks at setup.py*, comes here, meditates confused and hurt that anything this cool would use optparser over argparse, and not be packaged for the standard python packaging toolchain

I'm excited for this project though, sincerely. If it helps, here is the python packaging and distribution documentation I would recommend reading:

https://packaging.python.org/tutorials/distributing-packages/

There is also an example repository, https://github.com/pypa/sampleproject/

I also found it unclear how to use packaged data files, this may help: https://stackoverflow.com/a/5601839

**Comment by loxaxs** [comment]
#248 #264 #273
